In [8]:
import bs4
import requests
import pandas as pd
import re

In [9]:
page = 1
date_list = []
Topic_list = []
descrip_list = []
while page <= 29 :
    data = requests.get('https://www.bbc.co.uk/search?q=crime+thailand&page=' + str(page))
    soup = bs4.BeautifulSoup(data.text)
    for n in soup.find_all('div',{'class':'ssrcss-dirbxo-PromoSwitchLayoutAtBreakpoints e3z3r3u0'}):
        date_list.append(n.find('div',{'class':'ssrcss-m5j4pi-MetadataContent e1ojgjhb0'}).text.replace('\n',''))
        Topic_list.append(n.find('div',{'class':'ssrcss-1f3bvyz-Stack e1y4nx260'}).find('span',{'role':'text'}).text)
        descrip_list.append(n.find('p',{'class':'ssrcss-1q0x1qg-Paragraph eq5iqo00'}).text)
    print('Complete page number: ',page)
    page += 1
table = pd.DataFrame([date_list,Topic_list,descrip_list]).transpose()
table.columns = ['date','Topic','descrip']
table.set_index('date')

Complete page number:  1
Complete page number:  2
Complete page number:  3
Complete page number:  4
Complete page number:  5
Complete page number:  6
Complete page number:  7
Complete page number:  8
Complete page number:  9
Complete page number:  10
Complete page number:  11
Complete page number:  12
Complete page number:  13
Complete page number:  14
Complete page number:  15
Complete page number:  16
Complete page number:  17
Complete page number:  18
Complete page number:  19
Complete page number:  20
Complete page number:  21
Complete page number:  22
Complete page number:  23
Complete page number:  24
Complete page number:  25
Complete page number:  26
Complete page number:  27
Complete page number:  28
Complete page number:  29

,Topic,descrip
date,,
Programmes,Thailand: Earth's Tropical Paradise,Three-part documentary series exploring the tr...
15 January 2021,Thailand's Youth Rebellion,"For five months, young protesters in Thailand ..."
15 January 2021,Thailand's Youth Rebellion,"For five months, young protesters in Thailand ..."
Programmes,Heart of Thailand,Musician and conductor Jason Lai is in Bangkok...
Programmes,Thailand to Shetland,Jane Moncrieff discovers from catalogue brides...
...,...,...
9 September 2019,"Go Jetters: Series 3: Monkey Bay, Thailand",Things take a chilly turn when some cheeky mon...
31 August 2021,Ben Davis: Oxford United sign Thailand youth m...,Oxford United sign Thailand youth internationa...
17 November,Cumbria Police enlist volunteer horse riders t...,The six volunteers will work during the day to...
26 January,Blue Diamond Affair: Saudis end dispute with T...,Diplomatic ties resume after a 30-year row ove...
21 July 2021,"MotoGP: Thailand Grand Prix cancelled, Dani Pe...",MotoGP's Thailand Grand Prix is cancelled afte...

In [10]:
news_data = table.loc[~table['date'].isin(['Programmes'])]
news_data

,date,Topic,descrip
1,15 January 2021,Thailand's Youth Rebellion,"For five months, young protesters in Thailand ..."
2,15 January 2021,Thailand's Youth Rebellion,"For five months, young protesters in Thailand ..."
5,19 December,Thailand warship capsizes during storm,Video from the Thai Navy shows the ship on its...
6,19 December,Thailand warship capsizes leaving 31 sailors m...,The navy is searching for survivors after the ...
7,18 December,Armagh man Odhran O'Neill dies in kayaking inc...,Odhran O'Neill from Lurgan was last seen on Sa...
...,...,...,...
262,9 September 2019,"Go Jetters: Series 3: Monkey Bay, Thailand",Things take a chilly turn when some cheeky mon...
263,31 August 2021,Ben Davis: Oxford United sign Thailand youth m...,Oxford United sign Thailand youth internationa...
264,17 November,Cumbria Police enlist volunteer horse riders t...,The six volunteers will work during the day to...
265,26 January,Blue Diamond Affair: Saudis end dispute with T...,Diplomatic ties resume after a 30-year row ove...
266,21 July 2021,"MotoGP: Thailand Grand Prix cancelled, Dani Pe...",MotoGP's Thailand Grand Prix is cancelled afte...

In [11]:
from dsmlibrary.datanode import DataNode

In [12]:
dir_raw_id = 66

In [13]:
datanode = DataNode()

Init DataNode sucessful!

In [15]:
datanode.upload_file(directory_id=dir_raw_id, file_path='ข่าวอาชญากรรมไทยและต่างประเทศ.csv')

  0%|          | 0.00/29.3k [00:00<?, ?B/s]

{'id': 1056,
 'msg': 'file ข่าวอาชญากรรมไทยและต่างประเทศ.csv create sucessful',
 'path': 'nutcha/DSI310-11/rawData/ข่าวอาชญากรรมไทยและต่างประเทศ.csv',
 'uploaded': True}